---
# tasks file for backup_old_files role
- name: rename
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: "{{ item.mode }}"
  with_items:
    - { src: '/path/to/dir/app/application.yml', dest: '/path/to/dir/app/application_old.yml', mode: '0755' }
    - { src: '/path/to/dir/app/config.conf', dest: '/path/to/dir/app/config_old.conf', mode: '0755' }
    - { src: '/path/to/dir/app/my_app.jar', dest: '/path/to/dir/app/my_app_old.jar', mode: '0755' }
  become: true
  become_user: "{{user1 }}"