- name: start sevice
  ansible.builtin.service:
     name: "{{service_name}}"
     state: "started"

- name: Wait for service to be ready
  wait_for:
    port: "{{port_number}}"
    host: "{{host_ip}}"
    connect_timeout: "{{connect_timeout_sec}}"
    delay: "{{delay_Sec}}"
    timeout: "{{timeout_sec}}"
